# File xây dựng vector store, lưu trữ các schema table

## Pipeline bao gồm
- Xây dựng collection
- Thêm data và metadata vào collection
- Lựa chọn kĩ thuật RAG

In [ ]:
import re
import json
import torch
import pandas as pd
from langchain_chroma import Chroma
from sentence_transformers import SentenceTransformer

d:\python-workspace\NL2SQL-chat\myenv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### Tạo và thêm dữ liệu vào vector store

In [2]:
class EmbeddingModel:
    def __init__(self, model, device):
        self.model = SentenceTransformer(model, device=device)

    def embed_documents(self,data):
        return self.model.encode_document(data)

    def embed_query(self, query):
        return self.model.encode_query(query)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
embed_model = EmbeddingModel("all-MiniLM-L6-v2", device)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 10649.64it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [3]:
vector_store = Chroma(
    collection_name="first_collection",
    persist_directory="../vector-store",
    embedding_function=embed_model,
    collection_metadata={"hnsw:space": "cosine"}
)

In [ ]:
list_schema = ""
list_metadata = ""
with open("../schema_data/table_schema.txt", mode='r', encoding='utf-8') as f:
    list_schema = f.read()
with open("../schema_data/better_metadata.txt", mode='r', encoding='utf-8') as f:
    list_metadata = f.read()
list_schema = re.findall(r"CREATE TABLE.*?\);", list_schema, flags=re.DOTALL)
list_metadata = re.findall(r"{.*?}", list_metadata, flags=re.DOTALL)
print(f"Count schema: {len(list_schema)}")
print(f"Count metadata: {len(list_metadata)}")

In [ ]:
metadatas = [{"raw_context": schema} for schema in list_schema]
vector_store.add_texts(
    texts=list_metadata,
    metadatas=metadatas
)
print(f"Adding {len(list_schema)} table schema successful")

### Kiểm tra RAG

In [ ]:
query = "Find the total revenue generated from orders that were paid using 'Credit Card' and have already been shipped"

# Tìm kiếm top 2 bảng liên quan nhất
results = vector_store.similarity_search_with_relevance_scores(query, k=10)
print(results)
for i, doc in enumerate(results):
    print(f"\nKết quả {i+1}:")
    print(f"Điểm số liên quan: {doc[1]}")
    print(f"Nội dung tìm thấy: {doc[0].page_content}") # Đây là phần metadata enrichment
    # print(f"SQL Schema để ném vào LLM: {doc[0].metadata['raw_context']}")

[Document(id='c1651472-8ce3-4920-aa55-cee9ce6068ba', metadata={'raw_context': "CREATE TABLE Orders (\n    order_id SERIAL PRIMARY KEY,\n    user_id INT,\n    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n    total_amount DECIMAL(12, 2) NOT NULL,\n    status VARCHAR(50) DEFAULT 'Pending', \n    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE SET NULL\n);"}, page_content='{\n"table_name": "Orders",\n"table_description": "Stores information about customer transactions, including the total monetary value, current fulfillment status, and the timestamp of when the purchase was executed.",\n"columns_summary": "order_id: unique auto-incrementing identifier for the order | user_id: foreign key linking the order to the purchasing user | order_date: timestamp recording when the order was placed | total_amount: total calculated cost of the purchase | status: current tracking state of the order defaulting to Pending"\n}'), Document(id='a006f772-092f-4ae0-9667-6b7cfa0b3a02', metadata={'raw_context': 'CREATE TABLE Order_Items (\n    order_item_id SERIAL PRIMARY KEY,\n    order_id INT,\n    product_id INT,\n    quantity INT NOT NULL,\n    price_at_purchase DECIMAL(10, 2) NOT NULL,\n    FOREIGN KEY (order_id) REFERENCES Orders(order_id) ON DELETE CASCADE,\n    FOREIGN KEY (product_id) REFERENCES Products(product_id) ON DELETE SET NULL\n);'}, page_content='{\n"table_name": "Order_Items",\n"table_description": "Stores the individual items purchased within a specific order, acting as a historical record of products sold, their quantities, and the exact price paid at the time of the transaction.",\n"columns_summary": "order_item_id: unique auto-incrementing identifier for the line item | order_id: foreign key linking to the parent order | product_id: foreign key referencing the purchased product | quantity: number of units bought | price_at_purchase: the specific price of the product when the order was placed"\n}'), Document(id='edb042b2-daf9-4c5b-9355-c5e7f716d62d', metadata={'raw_context': "CREATE TABLE Payments (\n    payment_id SERIAL PRIMARY KEY,\n    order_id INT,\n    payment_method VARCHAR(50) NOT NULL, \n    amount DECIMAL(12, 2) NOT NULL,\n    status VARCHAR(50) DEFAULT 'Pending', \n    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n    FOREIGN KEY (order_id) REFERENCES Orders(order_id) ON DELETE CASCADE\n);"}, page_content='{\n"table_name": "Payments",\n"table_description": "Stores financial transaction records associated with customer orders, tracking the payment method used, monetary amount, and current processing status.",\n"columns_summary": "payment_id: unique auto-incrementing identifier for the transaction | order_id: foreign key linking to the associated customer order | payment_method: the specific mode of payment used such as credit card or digital wallet | amount: the total monetary value of the payment | status: current state of the transaction defaulting to Pending | transaction_date: timestamp recording when the payment was processed"\n}'), Document(id='45f61267-062b-43b6-ba9d-06ce0d7ea1d1', metadata={'raw_context': 'CREATE TABLE Cart_Items (\n    cart_item_id SERIAL PRIMARY KEY,\n    cart_id INT,\n    product_id INT,\n    quantity INT NOT NULL DEFAULT 1,\n    FOREIGN KEY (cart_id) REFERENCES Shopping_Cart(cart_id) ON DELETE CASCADE,\n    FOREIGN KEY (product_id) REFERENCES Products(product_id) ON DELETE CASCADE\n);'}, page_content='{\n"table_name": "Cart_Items",\n"table_description": "Stores the individual products and their quantities added to a specific user\'s shopping cart, acting as a junction between the shopping cart sessions and the products inventory.",\n"columns_summary": "cart_item_id: unique auto-incrementing identifier for the entry | cart_id: foreign key linking to the parent shopping cart session | product_id: foreign key indicating which specific product was added | quantity: number of units of the product added to the cart"\n}'), Document(id='de5fbc69-3f43-4798-92da-fac18a48100b', metadata={'raw_context': 'CREATE TABLE Shopping_Cart (\n    cart_id SERIAL PRIMARY KEY,\n    user_id INT,\n    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE\n);'}, page_content='{\n"table_name": "Shopping_Cart",\n"table_description": "Stores individual shopping cart sessions linked to specific users, tracking when the cart was initiated before checkout.",\n"columns_summary": "cart_id: unique auto-incrementing identifier for the cart | user_id: foreign key linking the cart to a specific user account | created_at: timestamp indicating when the shopping cart session began"\n}'), Document(id='74fc396e-05a2-4cf5-8d50-0f60ec18dbe5', metadata={'raw_context': "CREATE TABLE Shipping (\n    shipping_id SERIAL PRIMARY KEY,\n    order_id INT,\n    shipping_address TEXT NOT NULL,\n    tracking_number VARCHAR(100),\n    status VARCHAR(50) DEFAULT 'Preparing', \n    shipped_date TIMESTAMP NULL,\n    FOREIGN KEY (order_id) REFERENCES Orders(order_id) ON DELETE CASCADE\n);"}, page_content='{\n"table_name": "Shipping",\n"table_description": "Stores logistics and delivery tracking information for customer orders, detailing the destination physical address, courier tracking codes, and current dispatch status.",\n"columns_summary": "shipping_id: unique auto-incrementing identifier for the shipment record | order_id: foreign key linking to the associated customer order | shipping_address: destination physical address for the delivery | tracking_number: optional carrier code used to trace the package | status: current delivery state defaulting to Preparing | shipped_date: optional timestamp indicating exactly when the package was dispatched"\n}'), Document(id='e6ccf75e-874a-49dc-b66f-34460f486f1a', metadata={'raw_context': 'CREATE TABLE Products (\n    product_id SERIAL PRIMARY KEY,\n    product_name VARCHAR(255) NOT NULL,\n    price DECIMAL(10, 2) NOT NULL,\n    stock_quantity INT NOT NULL DEFAULT 0,\n    description TEXT,\n    category_id INT,\n    FOREIGN KEY (category_id) REFERENCES Categories(category_id) ON DELETE SET NULL\n);'}, page_content='{\n"table_name": "Products",\n"table_description": "Stores information about items available for sale, including pricing, inventory levels, detailed specifications, and references to their classification categories.",\n"columns_summary": "product_id: unique auto-incrementing identifier | product_name: required name or title of the product | price: numerical cost of the item | stock_quantity: current inventory count defaulting to zero | description: optional detailed text about the product | category_id: foreign key linking to the Categories table"\n}'), Document(id='d09b5296-2126-4a40-82db-5ed3b097e148', metadata={'raw_context': 'CREATE TABLE Reviews (\n    review_id SERIAL PRIMARY KEY,\n    user_id INT,\n    product_id INT,\n    rating INT CHECK (rating >= 1 AND rating <= 5),\n    comment TEXT,\n    review_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE SET NULL,\n    FOREIGN KEY (product_id) REFERENCES Products(product_id) ON DELETE CASCADE\n);'}, page_content='{\n"table_name": "Reviews",\n"table_description": "Stores customer feedback and evaluations for specific products, including a numerical score and written text.",\n"columns_summary": "review_id: unique auto-incrementing identifier for the review | user_id: foreign key linking to the authoring user | product_id: foreign key linking to the evaluated product | rating: numerical score from 1 to 5 indicating customer satisfaction | comment: optional detailed text of the user\'s review | review_date: timestamp recording when the review was created"\n}'), Document(id='17688f80-2d0a-460e-8fd0-5f87a211deb5', metadata={'raw_context': 'CREATE TABLE Users (\n    user_id SERIAL PRIMARY KEY,\n    full_name VARCHAR(100) NOT NULL,\n    email VARCHAR(100) UNIQUE NOT NULL,\n    password_hash VARCHAR(255) NOT NULL,\n    phone VARCHAR(20),\n    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);'}, page_content='{\n"table_name": "Users",\n"table_description": "Stores core user profile information including authentication credentials, contact details, and account creation timestamps for system access and identity management.",\n"columns_summary": "user_id: unique auto-incrementing identifier | full_name: complete name of the user | email: unique email address for contact and login | password_hash: securely encrypted password | phone: optional contact telephone number | created_at: timestamp when the account was registered"\n}'), Document(id='bd182174-b24c-4ffd-a112-eeeb2d005344', metadata={'raw_context': 'CREATE TABLE Categories (\n    category_id SERIAL PRIMARY KEY,\n    category_name VARCHAR(100) NOT NULL,\n    description TEXT\n);'}, page_content='{\n"table_name": "Categories",\n"table_description": "Stores logical groupings or classifications for items within the system, providing a name and detailed explanation for each category to organize data efficiently.",\n"columns_summary": "category_id: unique auto-incrementing identifier | category_name: required name of the classification | description: optional detailed text explaining the category\'s purpose or contents"\n}')]

Kết quả 1:

TypeError: 'Document' object is not subscriptable

In [7]:
from sentence_transformers import CrossEncoder

# ==========================================
# KHỞI TẠO MÔ HÌNH RERANKER
# ==========================================
print("Đang tải mô hình Cross-Encoder...")
reranker_model = CrossEncoder('BAAI/bge-reranker-base', device='cuda')

def two_stage_retrieval(query, vector_store, stage1_k=8, stage2_k=5):
    """
    Hàm truy xuất 2 giai đoạn:
    - Giai đoạn 1: Dùng ChromaDB lấy top 10 (chấp nhận điểm thấp, miễn là không sót).
    - Giai đoạn 2: Dùng Cross-Encoder chấm điểm lại và lấy top 5 đưa vào LLM.
    """
    
    # ---------------------------------------------------------
    # GIAI ĐOẠN 1: VECTOR RETRIEVAL (LẤY DIỆN RỘNG)
    # ---------------------------------------------------------
    # Gọi hàm similarity_search bình thường, không cần quan tâm ngưỡng điểm.
    # Lấy hẳn 15-20 bảng để đảm bảo bảng đúng (dù điểm 0.2) vẫn lọt vào danh sách này.
    print(f"\n[STAGE 1] Đang quét VectorDB lấy Top {stage1_k}...")
    stage1_docs = vector_store.similarity_search(query, k=stage1_k)
    
    # ---------------------------------------------------------
    # GIAI ĐOẠN 2: CROSS-ENCODER RERANKING (CHẤM ĐIỂM TINH)
    # ---------------------------------------------------------
    print("[STAGE 2] Đang Rerank lại các tài liệu...")
    
    # Tạo danh sách các cặp [Câu hỏi, Nội dung tài liệu]
    # Cross-Encoder yêu cầu đầu vào phải là một cặp đi liền nhau để nó so sánh chéo.
    sentence_pairs = [[query, doc.page_content] for doc in stage1_docs]
    # print("This is sentencec pairs: \n", sentence_pairs)

    # Mô hình dự đoán điểm số mới cho toàn bộ cặp này cùng lúc
    rerank_scores = reranker_model.predict(sentence_pairs)
    # print("This is rerank scores: \n", rerank_scores)
    
    # Ghép điểm số mới vào tài liệu tương ứng
    # Lưu ý: Convert điểm số thành float để dễ in ấn và so sánh
    scored_docs = []
    for doc, score in zip(stage1_docs, rerank_scores):
        scored_docs.append((doc, float(score)))
    
    # Sắp xếp danh sách giảm dần theo điểm số mới (từ cao xuống thấp)
    scored_docs.sort(key=lambda x: x[1], reverse=True)
    
    # Chỉ lấy Top K tài liệu xuất sắc nhất (ví dụ: 5 bảng)
    final_docs = scored_docs[:stage2_k]
    # print("This is final docs: \n", final_docs)
    
    return final_docs

# ==========================================
# CHẠY THỬ NGHIỆM
# ==========================================
user_query = "Find the total revenue generated from orders that were paid using 'Credit Card' and have already been shipped"

# Giả định vector_store là đối tượng Chroma của bạn
final_results = two_stage_retrieval(user_query, vector_store, stage1_k=8, stage2_k=5)
print(final_results)
print("\n[KẾT QUẢ CUỐI CÙNG SAU KHI RERANK]")
for i, (doc, score) in enumerate(final_results):
    content = doc.page_content
    print(f"Top {i+1} | Điểm Rerank: {score:.4f} | Nội dung bảng: \n", content)

Đang tải mô hình Cross-Encoder...

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 7815.76it/s]
XLMRobertaForSequenceClassification LOAD REPORT from: BAAI/bge-reranker-base
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...
[(Document(id='edb042b2-daf9-4c5b-9355-c5e7f716d62d', metadata={'raw_context': "CREATE TABLE Payments (\n    payment_id SERIAL PRIMARY KEY,\n    order_id INT,\n    payment_method VARCHAR(50) NOT NULL, \n    amount DECIMAL(12, 2) NOT NULL,\n    status VARCHAR(50) DEFAULT 'Pending', \n    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n    FOREIGN KEY (order_id) REFERENCES Orders(order_id) ON DELETE CASCADE\n);"}, page_content='{\n"table_name": "Payments",\n"table_description": "Stores financial transaction records associated with customer orders, tracking the payment method used, monetary amount, and current processing status.",\n"columns_summary": "payment_id: unique auto-incrementing identifier for the transaction | order_id: foreign key linking to the associated customer order | payment_method: the specific mode of payment used such as credit card or digital wallet | amount: the total monetary value of the payment | status: current state of the transaction defaulting to Pending | transaction_date: timestamp recording when the payment was processed"\n}'), 0.3877794146537781), (Document(id='c1651472-8ce3-4920-aa55-cee9ce6068ba', metadata={'raw_context': "CREATE TABLE Orders (\n    order_id SERIAL PRIMARY KEY,\n    user_id INT,\n    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n    total_amount DECIMAL(12, 2) NOT NULL,\n    status VARCHAR(50) DEFAULT 'Pending', \n    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE SET NULL\n);"}, page_content='{\n"table_name": "Orders",\n"table_description": "Stores information about customer transactions, including the total monetary value, current fulfillment status, and the timestamp of when the purchase was executed.",\n"columns_summary": "order_id: unique auto-incrementing identifier for the order | user_id: foreign key linking the order to the purchasing user | order_date: timestamp recording when the order was placed | total_amount: total calculated cost of the purchase | status: current tracking state of the order defaulting to Pending"\n}'), 0.09863540530204773), (Document(id='74fc396e-05a2-4cf5-8d50-0f60ec18dbe5', metadata={'raw_context': "CREATE TABLE Shipping (\n    shipping_id SERIAL PRIMARY KEY,\n    order_id INT,\n    shipping_address TEXT NOT NULL,\n    tracking_number VARCHAR(100),\n    status VARCHAR(50) DEFAULT 'Preparing', \n    shipped_date TIMESTAMP NULL,\n    FOREIGN KEY (order_id) REFERENCES Orders(order_id) ON DELETE CASCADE\n);"}, page_content='{\n"table_name": "Shipping",\n"table_description": "Stores logistics and delivery tracking information for customer orders, detailing the destination physical address, courier tracking codes, and current dispatch status.",\n"columns_summary": "shipping_id: unique auto-incrementing identifier for the shipment record | order_id: foreign key linking to the associated customer order | shipping_address: destination physical address for the delivery | tracking_number: optional carrier code used to trace the package | status: current delivery state defaulting to Preparing | shipped_date: optional timestamp indicating exactly when the package was dispatched"\n}'), 0.050417616963386536), (Document(id='a006f772-092f-4ae0-9667-6b7cfa0b3a02', metadata={'raw_context': 'CREATE TABLE Order_Items (\n    order_item_id SERIAL PRIMARY KEY,\n    order_id INT,\n    product_id INT,\n    quantity INT NOT NULL,\n    price_at_purchase DECIMAL(10, 2) NOT NULL,\n    FOREIGN KEY (order_id) REFERENCES Orders(order_id) ON DELETE CASCADE,\n    FOREIGN KEY (product_id) REFERENCES Products(product_id) ON DELETE SET NULL\n);'}, page_content='{\n"table_name": "Order_Items",\n"table_description": "Stores the individual items purchased within a specific order, acting as a historical record of products sold, their quantities, and the exact price paid at the time of the transaction.",\n"columns_summary": "order_item_id: unique auto-incrementing identifier for the line item | order_id: foreign key linking to the parent order | product_id: foreign key referencing the purchased product | quantity: number of units bought | price_at_purchase: the specific price of the product when the order was placed"\n}'), 0.013481847010552883), (Document(id='45f61267-062b-43b6-ba9d-06ce0d7ea1d1', metadata={'raw_context': 'CREATE TABLE Cart_Items (\n    cart_item_id SERIAL PRIMARY KEY,\n    cart_id INT,\n    product_id INT,\n    quantity INT NOT NULL DEFAULT 1,\n    FOREIGN KEY (cart_id) REFERENCES Shopping_Cart(cart_id) ON DELETE CASCADE,\n    FOREIGN KEY (product_id) REFERENCES Products(product_id) ON DELETE CASCADE\n);'}, page_content='{\n"table_name": "Cart_Items",\n"table_description": "Stores the individual products and their quantities added to a specific user\'s shopping cart, acting as a junction between the shopping cart sessions and the products inventory.",\n"columns_summary": "cart_item_id: unique auto-incrementing identifier for the entry | cart_id: foreign key linking to the parent shopping cart session | product_id: foreign key indicating which specific product was added | quantity: number of units of the product added to the cart"\n}'), 0.003408291144296527)]

[KẾT QUẢ CUỐI CÙNG SAU KHI RERANK]
Top 1 | Điểm Rerank: 0.3878 | Nội dung bảng:
 {
"table_name": "Payments",
"table_description": "Stores financial transaction records associated with customer orders, tracking the payment method used, monetary amount, and current processing status.",
"columns_summary": "payment_id: unique auto-incrementing identifier for the transaction | order_id: foreign key linking to the associated customer order | payment_method: the specific mode of payment used such as credit card or digital wallet | amount: the total monetary value of the payment | status: current state of the transaction defaulting to Pending | transaction_date: timestamp recording when the payment was processed"
}
Top 2 | Điểm Rerank: 0.0986 | Nội dung bảng:
 {
"table_name": "Orders",
"table_description": "Stores information about customer transactions, including the total monetary value, current fulfillment status, and the timestamp of when the purchase was executed.",
"columns_summary": "order_id: unique auto-incrementing identifier for the order | user_id: foreign key linking the order to the purchasing user | order_date: timestamp recording when the order was placed | total_amount: total calculated cost of the purchase | status: current tracking state of the order defaulting to Pending"
}
Top 3 | Điểm Rerank: 0.0504 | Nội dung bảng:
 {
"table_name": "Shipping",
"table_description": "Stores logistics and delivery tracking information for customer orders, detailing the destination physical address, courier tracking codes, and current dispatch status.",
"columns_summary": "shipping_id: unique auto-incrementing identifier for the shipment record | order_id: foreign key linking to the associated customer order | shipping_address: destination physical address for the delivery | tracking_number: optional carrier code used to trace the package | status: current delivery state defaulting to Preparing | shipped_date: optional timestamp indicating exactly when the package was dispatched"
}
Top 4 | Điểm Rerank: 0.0135 | Nội dung bảng:
 {
"table_name": "Order_Items",
"table_description": "Stores the individual items purchased within a specific order, acting as a historical record of products sold, their quantities, and the exact price paid at the time of the transaction.",
"columns_summary": "order_item_id: unique auto-incrementing identifier for the line item | order_id: foreign key linking to the parent order | product_id: foreign key referencing the purchased product | quantity: number of units bought | price_at_purchase: the specific price of the product when the order was placed"
}
Top 5 | Điểm Rerank: 0.0034 | Nội dung bảng:
 {
"table_name": "Cart_Items",
"table_description": "Stores the individual products and their quantities added to a specific user's shopping cart, acting as a junction between the shopping cart sessions and the products inventory.",
"columns_summary": "cart_item_id: unique auto-incrementing identifier for the entry | cart_id: foreign key linking to the parent shopping cart session | product_id: foreign key indicating which specific product was added | quantity: number of units of the product added to the cart"
}

In [8]:
# vector_store.delete_collection()

### Đánh giá RAG truyền thống và RAG Re-ranker

In [9]:
eval_data = pd.read_csv("../schema_data/evaluate_rag.csv")
eval_data.head()

                                english_query  RAG_tables
0     Show all user profiles created in 2024.       Users
1   List the names of all product categories.  Categories
2  Find products with a price lower than $50.    Products
3         Count the number of pending orders.      Orders
4    Retrieve all reviews with a rating of 5.     Reviews

In [10]:
def count_table(vector_store, query, true_answer, rag_type='original'):
    true_answer = true_answer.split()
    rag_answer_dict = []
    if rag_type=='original':
        rag_answer = vector_store.similarity_search_with_relevance_scores(query, k=5)
        for doc in rag_answer:
            rag_answer_dict.append(json.loads(doc[0].page_content))
    elif rag_type=='reranker':
        rag_answer = two_stage_retrieval(query, vector_store)
        for doc in rag_answer:
            rag_answer_dict.append(json.loads(doc[0].page_content))
    else:
        print("Sai loại RAG")
        return -1
    rag_answer_lst = [data.get("table_name") for data in rag_answer_dict]
    count = 0
    for table_name in rag_answer_lst:
        if table_name in true_answer:
            count += 1
    return count == len(true_answer)

In [11]:
eval_result_original = eval_data.copy()
eval_result_original['result'] = eval_result_original.apply(lambda row: count_table(vector_store, row['english_query'], row['RAG_tables']), axis=1)
print("Truy vấn schema đúng: ", len(eval_result_original[eval_result_original['result'] == True]))
eval_result_original

Truy vấn schema đúng:  32

,english_query,RAG_tables,result
0,Show all user profiles created in 2024.,Users,True
1,List the names of all product categories.,Categories,True
2,Find products with a price lower than $50.,Products,True
3,Count the number of pending orders.,Orders,True
4,Retrieve all reviews with a rating of 5.,Reviews,True
5,List products belonging to the 'Electronics' c...,Products Categories,True
6,Show the full name and email of user with ID 10.,Users,True
7,Get the total amount of all orders placed by u...,Users Orders,False
8,List all items currently in the shopping cart ...,Shopping_Cart Cart_Items Products,True
9,Find the average price of products in each cat...,Products Categories,False
10,Show all orders that are currently being shipped.,Orders Shipping,True
11,List the products and their quantities for ord...,Order_Items Products,True
12,Find users who have used 'Credit Card' for pay...,Users Orders Payments,True
13,Retrieve the tracking number for order ID 123.,Shipping,True
14,Show the total revenue generated from the 'Fur...,Products Categories Order_Items,True
15,List users who have never placed an order.,Users Orders,True
16,Find the most expensive product ever purchased.,Products Order_Items,True
17,Count how many reviews each product has received.,Products Reviews,True
18,Show the shipping address for the latest order...,Users Orders Shipping,False
19,List products that are out of stock (quantity ...,Products,True
20,Calculate the total amount paid via 'PayPal' t...,Payments,True
21,Find the average rating given by user 'Bob'.,Users Reviews,True
22,Show order details including product names for...,Orders Order_Items Products,True
23,List categories that have more than 10 products.,Categories Products,True
24,Find the total number of items currently in al...,Cart_Items,True
25,Retrieve all products reviewed in the last 30 ...,Products Reviews,True
26,Show the payment status for order ID 99.,Payments,True
27,List users who have items in their cart but no...,Users Shopping_Cart Orders,True
28,Find the best-selling product name in January ...,Products Order_Items Orders,True
29,Get the shipping date and status for order ID 45.,Shipping,True
30,Find the names of all products purchased by us...,Users Orders Order_Items Products,False
31,Show the category names of all items currently...,Users Shopping_Cart Cart_Items Products Catego...,False
32,Calculate the total revenue from the 'Electron...,Categories Products Order_Items Orders Payments,False
33,List the names of users who gave a 5-star revi...,Users Reviews Products Categories,False
34,Find the most popular product category among u...,Users Orders Order_Items Products Categories,False
35,What are the names of the products included in...,Shipping Orders Order_Items Products,True
36,Show the shipping addresses for all orders whe...,Payments Orders Users Shipping,False
37,List the email addresses of users who left a 1...,Users Reviews Products Order_Items Orders Ship...,False
38,Calculate the total dollar value of the items ...,Users Shopping_Cart Cart_Items Products,False
39,Identify the category that has generated the h...,Categories Products Order_Items Orders,True
40,How many units of 'Wireless Mouse' are current...,Products Order_Items Orders Shipping,True
41,List the full names of users who have an order...,Users Orders Payments Shipping,False
42,Find all users who purchased 'Smartphone X' an...,Users Orders Order_Items Products Reviews,False
43,Which user has the highest number of 'Clothing...,Categories Products Cart_Items Shopping_Cart U...,False
44,Find the average price of products purchased u...,Payments Orders Order_Items Products Categories,False
45,Show the comments of 5-star reviews for produc...,Reviews Products Order_Items Orders Shipping,True
46,Get the emails of all users who have reviewed ...,Categories Products Reviews Users,False
47,List the product names purchased by users crea...,Users Orders Payments Order_Items Products,False
48,Retrieve the full names and phone numbers of u...,Shipping Orders Payments Users,True
49,Calculate the total potential revenue of 'Furn...,Categories Products Cart_Items Shopping_Cart U...,False

In [12]:
eval_result_reranker = eval_data.copy()
eval_result_reranker['result'] = eval_result_reranker.apply(lambda row: count_table(vector_store, row['english_query'], row['RAG_tables'], rag_type='reranker'), axis=1)
print("Truy vấn schema đúng: ", len(eval_result_reranker[eval_result_reranker['result'] == True]))
eval_result_reranker

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...

[STAGE 1] Đang quét VectorDB lấy Top 8...
[STAGE 2] Đang Rerank lại các tài liệu...
Truy vấn schema đúng:  29

,english_query,RAG_tables,result
0,Show all user profiles created in 2024.,Users,True
1,List the names of all product categories.,Categories,True
2,Find products with a price lower than $50.,Products,True
3,Count the number of pending orders.,Orders,True
4,Retrieve all reviews with a rating of 5.,Reviews,True
5,List products belonging to the 'Electronics' c...,Products Categories,True
6,Show the full name and email of user with ID 10.,Users,True
7,Get the total amount of all orders placed by u...,Users Orders,False
8,List all items currently in the shopping cart ...,Shopping_Cart Cart_Items Products,False
9,Find the average price of products in each cat...,Products Categories,True
10,Show all orders that are currently being shipped.,Orders Shipping,True
11,List the products and their quantities for ord...,Order_Items Products,True
12,Find users who have used 'Credit Card' for pay...,Users Orders Payments,True
13,Retrieve the tracking number for order ID 123.,Shipping,True
14,Show the total revenue generated from the 'Fur...,Products Categories Order_Items,True
15,List users who have never placed an order.,Users Orders,False
16,Find the most expensive product ever purchased.,Products Order_Items,True
17,Count how many reviews each product has received.,Products Reviews,True
18,Show the shipping address for the latest order...,Users Orders Shipping,False
19,List products that are out of stock (quantity ...,Products,True
20,Calculate the total amount paid via 'PayPal' t...,Payments,True
21,Find the average rating given by user 'Bob'.,Users Reviews,False
22,Show order details including product names for...,Orders Order_Items Products,True
23,List categories that have more than 10 products.,Categories Products,True
24,Find the total number of items currently in al...,Cart_Items,True
25,Retrieve all products reviewed in the last 30 ...,Products Reviews,True
26,Show the payment status for order ID 99.,Payments,True
27,List users who have items in their cart but no...,Users Shopping_Cart Orders,False
28,Find the best-selling product name in January ...,Products Order_Items Orders,True
29,Get the shipping date and status for order ID 45.,Shipping,True
30,Find the names of all products purchased by us...,Users Orders Order_Items Products,False
31,Show the category names of all items currently...,Users Shopping_Cart Cart_Items Products Catego...,False
32,Calculate the total revenue from the 'Electron...,Categories Products Order_Items Orders Payments,False
33,List the names of users who gave a 5-star revi...,Users Reviews Products Categories,False
34,Find the most popular product category among u...,Users Orders Order_Items Products Categories,False
35,What are the names of the products included in...,Shipping Orders Order_Items Products,True
36,Show the shipping addresses for all orders whe...,Payments Orders Users Shipping,True
37,List the email addresses of users who left a 1...,Users Reviews Products Order_Items Orders Ship...,False
38,Calculate the total dollar value of the items ...,Users Shopping_Cart Cart_Items Products,False
39,Identify the category that has generated the h...,Categories Products Order_Items Orders,True
40,How many units of 'Wireless Mouse' are current...,Products Order_Items Orders Shipping,False
41,List the full names of users who have an order...,Users Orders Payments Shipping,True
42,Find all users who purchased 'Smartphone X' an...,Users Orders Order_Items Products Reviews,False
43,Which user has the highest number of 'Clothing...,Categories Products Cart_Items Shopping_Cart U...,False
44,Find the average price of products purchased u...,Payments Orders Order_Items Products Categories,False
45,Show the comments of 5-star reviews for produc...,Reviews Products Order_Items Orders Shipping,False
46,Get the emails of all users who have reviewed ...,Categories Products Reviews Users,False
47,List the product names purchased by users crea...,Users Orders Payments Order_Items Products,False
48,Retrieve the full names and phone numbers of u...,Shipping Orders Payments Users,True
49,Calculate the total potential revenue of 'Furn...,Categories Products Cart_Items Shopping_Cart U...,False